services:
  mysql:
    image: mysql:9.1.0
    container_name: hackathon-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    ports:
      - 3018:3306
    volumes:
      - ./db_init/:/docker-entrypoint-initdb.d
      - ./db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s          # Time between health checks
      timeout: 5s            # Time for each health check to timeout
      retries: 5             # Number of retries before marking as unhealthy
      start_period: 30s 

  spring-app:
    build: ./backend
    ports:
      - "3017:3017"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - spring-net
    depends_on:
      - mysql

networks:
  spring-net:
    driver: bridge